# Generated by Django 5.2.14 on 2026-05-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reaction_type', models.CharField(choices=[('like', "👍 J'aime"), ('love', "❤️ J'adore"), ('wow', '😮 Wow'), ('clap', '👏 Bravo'), ('fire', '🔥 Incroyable'), ('bookmark', '🔖 Sauvegarder')], max_length=20)),
                ('session_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Réaction',
                'verbose_name_plural': 'Réactions',
                'unique_together': {('content_type', 'object_id', 'reaction_type', 'session_key')},
            },
        ),
    ]
