# Generated by Django 5.2.14 on 2026-05-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_website',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_author_reply',
            field=models.BooleanField(default=False, verbose_name="Réponse de l'auteur"),
        ),
    ]
