# Generated by Django 5.2.14 on 2026-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_from_name',
            field=models.CharField(blank=True, default='Landry Net', help_text="Nom d'expéditeur de la newsletter", max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_intro_text',
            field=models.TextField(blank=True, default='Bonjour ! Voici une nouvelle publication sur le site.', help_text="Texte d'introduction des emails de newsletter"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_send_on_publish',
            field=models.BooleanField(default=False, help_text='Envoyer automatiquement la newsletter aux abonnés à chaque nouvelle publication'),
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('object_title', models.CharField(blank=True, max_length=300)),
                ('object_slug', models.CharField(blank=True, max_length=350)),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Vue de page',
                'verbose_name_plural': 'Vues de pages',
                'ordering': ['-date', '-count'],
                'unique_together': {('content_type', 'object_id', 'date')},
            },
        ),
    ]
