# Generated by Django 5.2.14 on 2026-05-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_newsletter_from_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_api_base_url',
            field=models.CharField(blank=True, default='https://api.chatanywhere.tech/v1', help_text='URL de base de votre API. ChatAnywhere: https://api.chatanywhere.tech/v1', max_length=300, verbose_name='URL de base API'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Votre clé API (compatible OpenAI). Ex: sk-...', max_length=500, verbose_name='Clé API IA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_enabled',
            field=models.BooleanField(default=False, verbose_name="Activer l'assistant IA"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-3.5-turbo', help_text='Nom du modèle. Ex: gpt-3.5-turbo, gpt-4, gpt-4o-mini', max_length=100, verbose_name='Modèle IA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_system_prompt',
            field=models.TextField(blank=True, help_text='Laissez vide pour utiliser le prompt par défaut.', verbose_name='Prompt système personnalisé'),
        ),
    ]
