# Generated by Django 5.2.14 on 2026-05-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_ai_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_sitemap_url',
            field=models.URLField(blank=True, help_text='Lien de votre sitemap à soumettre à Google Search Console. Ex: https://votresite.com/sitemap.xml', verbose_name='URL du Sitemap Google'),
        ),
    ]
