# Generated by Django 5.2.14 on 2026-05-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_google_sitemap_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('icon', models.CharField(blank=True, help_text='Ex: bi-code-slash | bi-database-fill | bi-filetype-py — ou emoji: 🐍 ⚛️', max_length=100, verbose_name='Icône Bootstrap Icons ou emoji')),
                ('color', models.CharField(default='#4F46E5', help_text='Ex: #4F46E5', max_length=7, verbose_name='Couleur hex')),
                ('url', models.URLField(blank=True, verbose_name='Lien documentation (optionnel)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
    ]
