# Generated by Django 5.2.14 on 2026-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(blank=True, default='#4F46E5', max_length=20),
        ),
    ]
